export const chiefComplaintsArr = [
  { key: "Frequent Snoring", value: false },
  { key: "Snoring which affects the sleep of others", value: false },
  { key: "Excessive daytime sleepiness", value: false },
  {
    key: "Others have observed that I stop breathing while I sleep",
    value: false,
  },
  { key: "Difficulty falling asleep", value: false },
  { key: "Difficulty in maintaining sleep", value: false },
  { key: "Walking up gasping", value: false },
  { key: "Choking while sleeping", value: false },
  { key: "Nightmare heartburn GRED", value: false },
  { key: "Feeling unrefreshed in the morning", value: false },
  { key: "Morning headaches", value: false },
  {
    key: "Nasal problems or difficulty breathing through the nose",
    value: false,
  },
  { key: "Clenching or grinding teeth at night ", value: false },
  { key: "TMJ or jaw pain", value: false },
  { key: "Neck or facial pain", value: false },
  { key: "Sounds in jaw joint(clicking, popping or grating)", value: false },
  { key: "I have been told that I stop breathing when I sleep", value: false },
  { key: "Memory problems", value: false },
  { key: "Irritability or mood swings", value: false },
];

export const cpapChiefComplintsArr = [
  { key: "Mask leaks", value: false },
  { key: "An inability to get the mask to fit properly", value: false },
  { key: "Discomfort from the straps or headgear", value: false },
  {
    key: "Decreased sleep quality or interrupted sleep from the CPAP device",
    value: false,
  },
  {
    key: "Noise from the device disrupting sleep and/or bedtime partners sleep",
    value: false,
  },
  { key: " CPAP restricted movements during sleep", value: false },
  { key: "CPAP does not solve my sleep problems (ineffective)", value: false },
  { key: "Device causes teeth or jaw problems", value: false },
  { key: "A latex allergy", value: false },
  { key: "Device causing claustrophobia or panic attacks", value: false },
  { key: "An unconscious need to remove the CPAP at night", value: false },
  { key: "GI/Stomach/Intestinal", value: false },
  { key: "The CPAP device irritated nasal passages", value: false },
  { key: "Inability to wear due to nasal problems", value: false },
  { key: "CPAP caused dry nose and/or mouth", value: false },
  { key: "The device caused eye irritation due to air leak", value: false },
];

export const allergens = [
  { key: "Acrylic", value: false },
  { key: "Antibiotics", value: false },
  { key: "Aspirin", value: false },
  { key: "Barbiturates", value: false },
  { key: "Codeine", value: false },
  { key: "Iodine", value: false },
  { key: "Latex", value: false },
  { key: "Jewelry", value: false },
  { key: "Local anesthetics", value: false },
  { key: "Metals", value: false },
  { key: "Penicillin", value: false },
  { key: "Plastic", value: false },
  { key: "Sedatives", value: false },
  { key: "Sleeping pills", value: false },
  { key: "Sulfa drugs", value: false },
];

export const medicationList = [
  { key: "Antacids", value: false },
  { key: "Antibiotics", value: false },
  { key: "Anticoagulants", value: false },
  { key: "Antidepressants", value: false },
  { key: "Anti-inflammatory drugs (Non-steroid)", value: false },
  { key: "Barbiturates", value: false },
  { key: "Blood thinners", value: false },
  { key: "Codeine", value: false },
  { key: "Cortisone", value: false },
  { key: "Diet pills", value: false },
  { key: "Heart medication", value: false },
  { key: "High blood pressure medication", value: false },
  { key: "Insulin", value: false },
  { key: "Muscle relaxants", value: false },
  { key: "Nerve pills", value: false },
  { key: "Pain medication", value: false },
  { key: "Sleeping pills", value: false },
  { key: "Sulfa drugs", value: false },
  { key: "Tranquilizers", value: false },
  { key: "Coumadin", value: false },
];

export const dentalHistoryList = [
  { key: "Do you wear removable partials?", value: "", state: false },
  {
    key: "Do you, or have you ever worn orthodontics?",
    value: "",
    state: false,
  },
  {
    key: "Do you have pain in your jaw joint?",
    value: "",
    state: false,
  },
  {
    key: "Have you ever had an injury to your head, face, neck, mouth, or teeth?",
    value: "",
    state: false,
  },
  {
    key: "Have you ever had gum problems?",
    value: "",
    state: false,
  },
  {
    key: "Are you planning to have dental work done in the near future?",
    value: "",
    state: false,
  },
  {
    key: "Have you ever had teeth extracted?",
    value: "",
    state: false,
  },
  {
    key: "Do you wear dentures?",
    value: "",
    state: false,
  },
  {
    key: "Does your TMJ (jaw joint) click or pop?",
    value: "",
    state: false,
  },
  {
    key: "Have you had TMJ (jaw joint) surgery?",
    value: "",
    state: false,
  },
  {
    key: "Do you have morning dry mouth?",
    value: "",
    state: false,
  },
  {
    key: "Have you ever had gum surgery?",
    value: "",
    state: false,
  },
  {
    key: "Do you clench or grind your teeth?",
    value: "",
    state: false,
  },
];

export const numberArr = [
  { label: 0, value: 0 },
  { label: 1, value: 2 },
  { label: 3, value: 3 },
  { label: 4, value: 4 },
  { label: 5, value: 5 },
  { label: 6, value: 6 },
  { label: 7, value: 7 },
  { label: 8, value: 8 },
  { label: 9, value: 9 },
  { label: 10, value: 10 },
];
export const confirmArr = [
  { label: "Yes", value: "Yes" },
  { label: "No", value: "No" },
];
export const confirmExtraArr = [
  { label: "Yes", value: "Yes" },
  { label: "No", value: "No" },
  { label: "Sometimes", value: "Sometimes" },
];

export const states = [
  "Alabama",
  "Alaska",
  "American Samoa",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Federated States of Micronesia",
  "Florida",
  "Georgia",
  "Guam",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Marshall Islands",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Northern Mariana Islands",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Palau",
  "Pennsylvania",
  "Puerto Rico",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virgin Island",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];
