export default [
  {
    name: 'Natus enim cumque libero ad voluptatibus.\nVoluptate nostrum repellat necessitatibus.',
    asking_price: 8623065.78,
    address: '967 Lesch Plains, Adolphusstad, Romania',
    coordinates: { lat: '51.1646', lng: '101.5941' },
    house_info: { bed: '4', bath: '9', garage: '3', sqft: '7759' },
    house_type: 'Vacant Land',
    image: 'https://loremflickr.com/508/525/city',
  },
  {
    name: 'Soluta veniam distinctio doloribus rerum itaque nesciunt.\nSaepe tenetur dolores.',
    asking_price: 8468145.22,
    address: '688 Keeling Rapids, South Hillard, Belgium',
    coordinates: { lat: '40.9872', lng: '-171.4969' },
    house_info: { bed: '6', bath: '2', garage: '9', sqft: '7076' },
    house_type: 'Commercial',
    image: 'https://loremflickr.com/510/550/city',
  },
  {
    name: 'Velit repudiandae facilis aut veritatis blanditiis optio totam.\nSunt iure corporis iusto ipsa impedit itaque ea autem.',
    asking_price: 4977136.2,
    address: '7714 Hilma Parkway, Allentown, Kuwait',
    coordinates: { lat: '-58.1461', lng: '-39.4252' },
    house_info: { bed: '1', bath: '8', garage: '8', sqft: '5346' },
    house_type: 'Residential',
    image: 'https://loremflickr.com/524/515/city',
  },
  {
    name: 'Neque aliquam mollitia aliquam quidem aut nam perspiciatis.\nAccusamus magnam accusamus cum velit dolores mollitia ab.',
    asking_price: 7419146.57,
    address: '61298 Darien Circles, Flint, Nicaragua',
    coordinates: { lat: '82.6367', lng: '-169.9551' },
    house_info: { bed: '7', bath: '6', garage: '7', sqft: '1847' },
    house_type: 'Vacant Land',
    image: 'https://loremflickr.com/585/528/city',
  },
  {
    name: 'Ea tenetur consectetur.\nBeatae doloribus earum modi eos sed.',
    asking_price: 8701449.93,
    address: '05229 Ethelyn Port, East Bretmouth, Turkey',
    coordinates: { lat: '-72.5183', lng: '-115.7322' },
    house_info: { bed: '6', bath: '6', garage: '5', sqft: '9326' },
    house_type: 'Commercial',
    image: 'https://loremflickr.com/521/578/city',
  },
  {
    name: 'Sequi voluptatibus tempora aliquam temporibus ipsum ipsum.\nPerferendis qui dolor in recusandae laudantium illo adipisci esse.',
    asking_price: 2178560,
    address: '1809 Rebeca Gateway, Coral Gables, Macedonia',
    coordinates: { lat: '-61.9830', lng: '-34.0931' },
    house_info: { bed: '3', bath: '2', garage: '8', sqft: '7679' },
    house_type: 'Residential',
    image: 'https://loremflickr.com/599/523/city',
  },
  {
    name: 'Repellat dolorem accusantium laudantium nobis mollitia ducimus.\nA eos illo alias enim tenetur.',
    asking_price: 9288521.72,
    address: '95301 Kenyatta Stravenue, Dietrichbury, Mauritius',
    coordinates: { lat: '-75.8785', lng: '74.8966' },
    house_info: { bed: '2', bath: '6', garage: '7', sqft: '1938' },
    house_type: 'Vacant Land',
    image: 'https://loremflickr.com/538/543/city',
  },
  {
    name: 'Sint corporis harum doloremque dolore commodi accusantium modi impedit.\nDoloribus adipisci aliquam minima praesentium magni.',
    asking_price: 5721167.91,
    address: '41013 Emmerich Lane, Santa Maria, Zimbabwe',
    coordinates: { lat: '-16.4054', lng: '-157.5729' },
    house_info: { bed: '7', bath: '1', garage: '7', sqft: '9577' },
    house_type: 'Vacant Land',
    image: 'https://loremflickr.com/539/590/city',
  },
  {
    name: 'Corrupti quia laboriosam quasi possimus dolor inventore officia.\nQuod odit repellendus.',
    asking_price: 546732.35,
    address: '2389 Raheem Plains, Sandy Springs, Trinidad and Tobago',
    coordinates: { lat: '46.4914', lng: '176.8141' },
    house_info: { bed: '4', bath: '2', garage: '2', sqft: '2525' },
    house_type: 'Residential',
    image: 'https://loremflickr.com/597/566/city',
  },
  {
    name: 'Similique voluptate numquam veniam placeat.\nExpedita perferendis eos dignissimos dolores.',
    asking_price: 8090289.99,
    address: '111 Ruby Shores, Vallejo, New Caledonia',
    coordinates: { lat: '6.8217', lng: '-5.0662' },
    house_info: { bed: '1', bath: '5', garage: '9', sqft: '1184' },
    house_type: 'Residential',
    image: 'https://loremflickr.com/563/508/city',
  },
  {
    name: 'Architecto labore doloremque tempora repellat explicabo commodi minus dolorem nemo.\nDeleniti delectus ex.',
    asking_price: 4636112.49,
    address: '75973 Loy Track, Fort Arjunburgh, Venezuela',
    coordinates: { lat: '89.7881', lng: '-56.5727' },
    house_info: { bed: '2', bath: '5', garage: '4', sqft: '3570' },
    house_type: 'Residential',
    image: 'https://loremflickr.com/599/539/city',
  },
  {
    name: 'Magni sint quam unde iste voluptate.\nMollitia earum beatae similique est.',
    asking_price: 7436768.2,
    address: '531 Dejuan Circles, West Adrain, Brunei Darussalam',
    coordinates: { lat: '46.2893', lng: '179.1261' },
    house_info: { bed: '9', bath: '7', garage: '7', sqft: '4230' },
    house_type: 'Vacant Land',
    image: 'https://loremflickr.com/567/584/city',
  },
  {
    name: 'Perspiciatis nobis eos maiores ipsam.\nVoluptatem hic quisquam minima voluptates cum eius asperiores.',
    asking_price: 6060982.77,
    address: '2120 Lennie Stravenue, Heaneystead, Finland',
    coordinates: { lat: '3.3420', lng: '-137.0612' },
    house_info: { bed: '6', bath: '9', garage: '1', sqft: '1580' },
    house_type: 'Vacant Land',
    image: 'https://loremflickr.com/568/533/city',
  },
  {
    name: 'Consectetur eum voluptate libero.\nCorporis perferendis ullam quas perferendis nihil labore temporibus sed.',
    asking_price: 4251214.75,
    address: '55680 Alfonso Plain, Fort Rowena, Malaysia',
    coordinates: { lat: '-32.7389', lng: '-97.6986' },
    house_info: { bed: '7', bath: '7', garage: '5', sqft: '5188' },
    house_type: 'Commercial',
    image: 'https://loremflickr.com/599/514/city',
  },
  {
    name: 'Beatae hic dolores laborum itaque delectus est alias.\nMinima sequi voluptate voluptate quia dicta sapiente porro.',
    asking_price: 3213562.18,
    address: '936 Cronin Corners, Marquardttown, Saint Pierre and Miquelon',
    coordinates: { lat: '32.5656', lng: '48.1644' },
    house_info: { bed: '4', bath: '1', garage: '7', sqft: '8826' },
    house_type: 'Commercial',
    image: 'https://loremflickr.com/523/561/city',
  },
  {
    name: 'Velit quas dignissimos corrupti fuga voluptatum.\nCorporis illum velit saepe pariatur.',
    asking_price: 7838961.54,
    address: '860 Vandervort Trace, Eau Claire, Mozambique',
    coordinates: { lat: '69.9738', lng: '-71.5948' },
    house_info: { bed: '4', bath: '2', garage: '1', sqft: '6910' },
    house_type: 'Commercial',
    image: 'https://loremflickr.com/564/556/city',
  },
  {
    name: 'Cupiditate natus deserunt repellendus dicta voluptatem.\nOfficia architecto voluptatem tempora id perferendis voluptate.',
    asking_price: 6610874.44,
    address: '622 Bashirian Ridges, Norvalchester, Slovakia (Slovak Republic)',
    coordinates: { lat: '69.7860', lng: '-72.1266' },
    house_info: { bed: '4', bath: '5', garage: '9', sqft: '4946' },
    house_type: 'Residential',
    image: 'https://loremflickr.com/545/515/city',
  },
  {
    name: 'Nihil aliquam et corrupti culpa ipsa.\nDolore ipsa animi quis.',
    asking_price: 2511940.38,
    address: '325 Glenda Underpass, Ivyworth, Senegal',
    coordinates: { lat: '-3.5472', lng: '-7.7202' },
    house_info: { bed: '9', bath: '5', garage: '6', sqft: '9763' },
    house_type: 'Residential',
    image: 'https://loremflickr.com/544/554/city',
  },
  {
    name: 'Fugit porro eaque laboriosam.\nIllo eaque accusamus error libero.',
    asking_price: 9330207.16,
    address: '41359 Durgan Shoals, South Seanburgh, Kazakhstan',
    coordinates: { lat: '16.0603', lng: '-44.6844' },
    house_info: { bed: '7', bath: '8', garage: '8', sqft: '8667' },
    house_type: 'Vacant Land',
    image: 'https://loremflickr.com/506/549/city',
  },
  {
    name: 'Voluptatem sapiente velit assumenda dolore eum repellendus consequuntur aliquid quis.\nNam in adipisci occaecati a veniam ut eos totam voluptatem.',
    asking_price: 7431011.45,
    address: '90711 Alaina Isle, Kertzmannborough, Mauritania',
    coordinates: { lat: '39.5801', lng: '75.4041' },
    house_info: { bed: '1', bath: '8', garage: '2', sqft: '2413' },
    house_type: 'Commercial',
    image: 'https://loremflickr.com/512/566/city',
  },
];
